# Generated by Django 3.1.3 on 2020-11-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.IntegerField(choices=[(0, 'Nieznany'), (1, 'Podstawowy'), (2, 'Rozszerzony')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(2, 'Zamknięte'), (1, 'Otwarte'), (3, 'Krótka odpowiedź'), (0, 'Nieznany')]),
        ),
    ]
