# Generated by Django 3.0.5 on 2020-05-07 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=500)),
                ('add_date', models.DateField()),
                ('is_open', models.BinaryField()),
                ('author', models.CharField(max_length=100)),
                ('true_false', models.BinaryField()),
                ('abcd', models.BinaryField()),
                ('difficulty', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
