# Generated by Django 3.1.3 on 2020-12-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='answers',
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.IntegerField(choices=[(0, 'Nieznany'), (2, 'Rozszerzony'), (1, 'Podstawowy')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(1, 'Otwarte'), (0, 'Nieznany'), (2, 'Zamknięte'), (3, 'Krótka odpowiedź')]),
        ),
    ]
