# Generated by Django 3.0.6 on 2020-10-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.IntegerField(choices=[(1, 'Podstawowy'), (0, 'Nieznany'), (2, 'Rozszerzony')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(0, 'Nieznany'), (2, 'Zamknięte'), (1, 'Otwarte'), (3, 'Krótka odpowiedź')], default=0),
        ),
    ]
