# Generated by Django 3.1.3 on 2020-11-13 17:41

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variables', django_mysql.models.ListCharField(models.CharField(max_length=200), default=None, max_length=1320, size=6)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.IntegerField(choices=[(1, 'Podstawowy'), (2, 'Rozszerzony'), (0, 'Nieznany')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(2, 'Zamknięte'), (1, 'Otwarte'), (0, 'Nieznany'), (3, 'Krótka odpowiedź')], default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='variables',
            field=models.ManyToManyField(to='authentication.Variables'),
        ),
    ]
