# Generated by Django 3.0.6 on 2020-10-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201028_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.IntegerField(choices=[(2, 'Rozszerzony'), (1, 'Podstawowy'), (0, 'Nieznany')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(3, 'Krótka odpowiedź'), (2, 'Zamknięte'), (1, 'Otwarte'), (0, 'Nieznany')], default=0),
        ),
    ]
