# Generated by Django 3.1.3 on 2020-12-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201201_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(0, 'Nieznany'), (1, 'Otwarte'), (2, 'Zamknięte'), (3, 'Krótka odpowiedź')]),
        ),
    ]
