# Generated by Django 3.1.3 on 2020-11-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201122_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.IntegerField(choices=[(2, 'Rozszerzony'), (1, 'Podstawowy'), (0, 'Nieznany')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(1, 'Otwarte'), (2, 'Zamknięte'), (3, 'Krótka odpowiedź'), (0, 'Nieznany')]),
        ),
    ]
