# Generated by Django 3.1.3 on 2020-11-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201113_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.IntegerField(choices=[(2, 'Rozszerzony'), (1, 'Podstawowy'), (0, 'Nieznany')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(3, 'Krótka odpowiedź'), (0, 'Nieznany'), (2, 'Zamknięte'), (1, 'Otwarte')], default=0),
        ),
    ]
