# Generated by Django 3.1.4 on 2021-01-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210103_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='spacetosolve',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='timetosolve',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.IntegerField(choices=[(2, 'Rozszerzony'), (1, 'Podstawowy'), (0, 'Nieznany')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(1, 'Otwarte'), (2, 'Zamknięte'), (3, 'Krótka odpowiedź'), (0, 'Nieznany')]),
        ),
    ]
