# Generated by Django 3.1.3 on 2020-11-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201122_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.IntegerField(choices=[(2, 'Rozszerzony'), (0, 'Nieznany'), (1, 'Podstawowy')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(3, 'Krótka odpowiedź'), (0, 'Nieznany'), (2, 'Zamknięte'), (1, 'Otwarte')]),
        ),
    ]
