# Generated by Django 3.1.3 on 2020-11-13 18:26

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201113_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='variables',
        ),
        migrations.AddField(
            model_name='answers',
            name='variables',
            field=django_mysql.models.ListCharField(models.CharField(max_length=200), default=None, max_length=1320, size=6),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.IntegerField(choices=[(1, 'Podstawowy'), (2, 'Rozszerzony'), (0, 'Nieznany')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(3, 'Krótka odpowiedź'), (2, 'Zamknięte'), (1, 'Otwarte'), (0, 'Nieznany')], default=0),
        ),
        migrations.DeleteModel(
            name='Variables',
        ),
    ]
