# Generated by Django 3.0.6 on 2020-10-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201029_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='section',
            field=models.ManyToManyField(to='authentication.Section'),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.IntegerField(choices=[(1, 'Podstawowy'), (2, 'Rozszerzony'), (0, 'Nieznany')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(2, 'Zamknięte'), (3, 'Krótka odpowiedź'), (0, 'Nieznany'), (1, 'Otwarte')], default=0),
        ),
    ]
