# Generated by Django 3.0.5 on 2020-05-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200507_2020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Tasksi',
        ),
    ]
