# Generated by Django 3.0.5 on 2020-05-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200507_2149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasksi',
            new_name='Tasks',
        ),
    ]
