# Generated by Django 3.0.6 on 2020-10-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20201029_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.IntegerField(choices=[(0, 'Nieznany'), (2, 'Rozszerzony'), (1, 'Podstawowy')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(2, 'Zamknięte'), (0, 'Nieznany'), (1, 'Otwarte'), (3, 'Krótka odpowiedź')], default=0),
        ),
    ]
