# Generated by Django 3.1.3 on 2020-11-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20201113_1826'),
        ('authentication', '0005_auto_20201030_1823'),
    ]

    operations = [
    ]
