# Generated by Django 3.1.4 on 2021-01-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210111_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecAndSkillhelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60000, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.IntegerField(choices=[(0, 'Nieznany'), (2, 'Rozszerzony'), (1, 'Podstawowy')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(0, 'Nieznany'), (1, 'Otwarte'), (2, 'Zamknięte'), (3, 'Krótka odpowiedź')]),
        ),
        migrations.AlterField(
            model_name='testjson',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
