# Generated by Django 3.0.5 on 2020-05-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20200508_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Umiejętność',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa_umiejetnosci', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='dział',
            old_name='Nazwa',
            new_name='Nazwa_dzialu',
        ),
    ]
