# Generated by Django 3.1.3 on 2020-11-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_merge_20201113_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='allanswers',
            new_name='wronganswers',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='variables',
        ),
        migrations.RemoveField(
            model_name='task',
            name='section',
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.IntegerField(choices=[(2, 'Rozszerzony'), (1, 'Podstawowy'), (0, 'Nieznany')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(1, 'Otwarte'), (2, 'Zamknięte'), (0, 'Nieznany'), (3, 'Krótka odpowiedź')], default=0),
        ),
    ]
