# Generated by Django 3.1.3 on 2020-11-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20201113_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.IntegerField(choices=[(0, 'Nieznany'), (1, 'Podstawowy'), (2, 'Rozszerzony')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(0, 'Nieznany'), (3, 'Krótka odpowiedź'), (2, 'Zamknięte'), (1, 'Otwarte')], default=0),
        ),
    ]
