# Generated by Django 3.0.5 on 2020-05-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20200508_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='abcd',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='task',
            name='true_false',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user_id',
        ),
    ]
