# Generated by Django 3.1.3 on 2020-11-14 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20201113_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='answers',
        ),
        migrations.AddField(
            model_name='task',
            name='answers',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='authentication.answers'),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.IntegerField(choices=[(2, 'Rozszerzony'), (1, 'Podstawowy'), (0, 'Nieznany')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(2, 'Zamknięte'), (0, 'Nieznany'), (1, 'Otwarte'), (3, 'Krótka odpowiedź')], default=0),
        ),
    ]
