# Generated by Django 3.0.5 on 2020-05-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20200508_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='typ',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
