# Generated by Django 3.1.3 on 2020-11-19 15:46

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20201114_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='task',
            name='add_date',
        ),
        migrations.AddField(
            model_name='skill',
            name='section',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='Section',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Skill',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='answers',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='authentication.answers'),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(default=authentication.models.CustomUser, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ManyToManyField(blank=True, to='authentication.Image'),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.IntegerField(choices=[(1, 'Podstawowy'), (2, 'Rozszerzony'), (0, 'Nieznany')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.CharField(max_length=600, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(1, 'Otwarte'), (2, 'Zamknięte'), (3, 'Krótka odpowiedź'), (0, 'Nieznany')]),
        ),
        migrations.CreateModel(
            name='Sectionv2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(max_length=500, unique=True)),
                ('skilll', models.ManyToManyField(blank=True, null=True, to='authentication.Skill')),
            ],
        ),
    ]
