# Generated by Django 3.0.5 on 2020-05-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20200508_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer',
            field=models.CharField(default='odp', max_length=500),
            preserve_default=False,
        ),
    ]
