# Generated by Django 3.1.3 on 2020-11-19 15:54

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20201119_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(blank=True, default=authentication.models.CustomUser, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.IntegerField(choices=[(2, 'Rozszerzony'), (0, 'Nieznany'), (1, 'Podstawowy')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(3, 'Krótka odpowiedź'), (1, 'Otwarte'), (0, 'Nieznany'), (2, 'Zamknięte')]),
        ),
    ]
