# Generated by Django 3.0.5 on 2020-05-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_task_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='task',
            name='level',
            field=models.CharField(default='podstawa', max_length=100),
            preserve_default=False,
        ),
    ]
