# Generated by Django 3.0.5 on 2020-05-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20200508_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='dział',
            name='tasks',
            field=models.ManyToManyField(to='authentication.Task'),
        ),
        migrations.AddField(
            model_name='umiejętność',
            name='tasks',
            field=models.ManyToManyField(to='authentication.Task'),
        ),
    ]
