# Generated by Django 3.0.5 on 2020-05-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20200508_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umiejętność',
            name='tasks',
        ),
        migrations.AddField(
            model_name='dział',
            name='skill',
            field=models.ManyToManyField(to='authentication.Umiejętność'),
        ),
        migrations.AddField(
            model_name='task',
            name='skilltask',
            field=models.ManyToManyField(to='authentication.Umiejętność'),
        ),
    ]
