# Generated by Django 3.0.6 on 2020-05-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_useractivationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivationtoken',
            name='used',
            field=models.DateTimeField(null=True),
        ),
    ]
